### ISSUE TITLE
Bug: Beta and RC versions do not seem to be available

### ISSUE THREAD

**Issue by nextgenthemes** [roots/wordpress#46] opened 2023-03-25 09:24 UTC
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

I am trying to install WP 6.2.0-RC4 but its not there.

#### What have you tried?

```
composer show -a roots/wordpress           
name     : roots/wordpress
descrip. : WordPress is web software you can use to create a beautiful website or blog.
keywords : blog, cms, wordpress
versions : 6.1.1, 6.1, 6.0.3, .... 3.7.38, dev-main, * dev-nightly
```
This has `dev-main` and `dev-nightly`. Both install `6.3-alpha-55584`

#### What insights have you gained?

because `roots/wordpress-no-content` is required and it has only `dev-main` and no `dev-nightly` but it seems that its pulled from wp nighty, trunk or whatever they call it.

There should be a branch for the latest beta and RC releases IMO. I ran into this issue b4. In a few days 6.2 it ready anyway but I like to try beta versions in the future.

#### Possible solutions

Something like `dev-beta` in composer. Or the actual version tags for upcoming WP versions.

#### Temporary workarounds

`wp core update --version=6.2-RC4 --force` works but it installs all the themes and the default plugins in the wrong directories. So not some kind of `no-content` version and it does not play nice with the Bedrock folder structure.

### Steps To Reproduce

1. Set to `dev-main` in composer
1. composer update
1. see latest alpha installed instead of beta/rc

### Expected Behavior

beta

### Actual Behavior

alpha

### Versions

6.1.1

**Comment by LeoColomb** [comment] 2023-03-25 10:57
Duplicate of https://github.com/roots/wordpress-no-content/issues/4

In short:
* `roots/wordpress-no-content` does not provide beta/RC version because WordPress.org does not either.
  * There is a ticket on WP track system for them to offer this option.
* `roots/wordpress-full` does provide every versions, with the cost of all the additional assets compared to `no-content`.
  * You can easily switch by removing `roots/wordpress` and adding both `roots/wordpress-core-installer` and `roots/wordpress-full` instead.

**Closed by LeoColomb** 2023-03-25 10:57 UTC
Labels: bug
